# Generated by Django 5.0.6 on 2024-06-28 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="brand",
        ),
    ]
