# Generated by Django 5.0.6 on 2024-06-28 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_brand_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="type",
            new_name="category",
        ),
    ]
